#!/usr/bin/python3

# Script to update course metadata information in all course files in course from a given CSV file

import csv, sys, re

inp=sys.argv[1]

fields = []

def get_location(row, string):
    location = 0;
    for s in row:
        if string == s:
            return location
        location = location + 1

    # Lol should never get here :P
    return -100


with open(inp) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0

    header = []
    for row in csv_reader:
        if line_count == 0:
            header = row

            for i in range(len(header)):
                # remove all special characters, blank space and get the name
                out = ''.join(filter(str.isalnum, header[i])).lower()
                fields.append(out)

        else:
            yq_update_str = ""
            for i in range(len(row)):
                # Update an entry only if there is some data
                if (len(row[i])):
                # Remove : as it gives trouble for jekyll to read data
                    yq_update_str += " ."+fields[i] + "=\"" + str(row[i].replace(":","-").replace("\n","")) + "\" |"

            # Remove the last |
            yq_update_str = yq_update_str[:-1]

            CODE = get_location(header, "Code")
            TITLE = get_location(header, "Title")
            print(f"yq eval -i '{yq_update_str}' {str(row[CODE]).lower()}-{row[TITLE].replace(' ', '-')}.md")

        line_count += 1

    # Small fix up to get rid of quotes generated by yq
    #  print("sed -i -e "s/['\"]\[/\[/g" -e "s/\]['\"]/\]/g" *.md") 
    #print(f'Processed {line_count} lines.')

