#!/usr/bin/bash
#python3 ./_scripts/csv2psql.py ./_data_csv/adjfaculty.csv adjfaculty > adjfaculty.sql
#python3 ./_scripts/csv2psql.py ./_data_csv/allfaculty.csv allfaculty > allfaculty.sql
#python3 ./_scripts/csv2psql.py ./_data_csv/announce.csv announce > announce.sql
#python3 ./_scripts/csv2psql.py ./_data_csv/awards.csv awards > awards.sql
python3 ./_scripts/csv2psql.py ./_data_csv/btechAlumni.csv btechAlumni > btechAlumni.sql
python3 ./_scripts/csv2psql.py ./_data_csv/btech.csv btech > btech.sql
python3 ./_scripts/csv2psql.py ./_data_csv/colloquium.csv colloquium > colloquium.sql
python3 ./_scripts/csv2psql.py ./_data_csv/courses_Core.csv courses_Core > courses_Core.sql
python3 ./_scripts/csv2psql.py ./_data_csv/courses.csv courses > courses.sql
python3 ./_scripts/csv2psql.py ./_data_csv/courses_Elective.csv courses_Elective > courses_Elective.sql
python3 ./_scripts/csv2psql.py ./_data_csv/cse_faculty.csv cse_faculty > cse_faculty.sql
python3 ./_scripts/csv2psql.py ./_data_csv/currentCourses.csv currentCourses > currentCourses.sql
python3 ./_scripts/csv2psql.py ./_data_csv/currentNPTELCourses.csv currentNPTELCourses > currentNPTELCourses.sql
python3 ./_scripts/csv2psql.py ./_data_csv/faculty.csv faculty > faculty.sql
python3 ./_scripts/csv2psql.py ./_data_csv/internship.csv internship > internship.sql
python3 ./_scripts/csv2psql.py ./_data_csv/mcamAlumni.csv mcamAlumni > mcamAlumni.sql
python3 ./_scripts/csv2psql.py ./_data_csv/mcam.csv mcam > mcam.sql
python3 ./_scripts/csv2psql.py ./_data_csv/msAlumni.csv msAlumni > msAlumni.sql
python3 ./_scripts/csv2psql.py ./_data_csv/msocdAlumni.csv msocdAlumni > msocdAlumni.sql
python3 ./_scripts/csv2psql.py ./_data_csv/msocd.csv msocd > msocd.sql
python3 ./_scripts/csv2psql.py ./_data_csv/openPos.csv openPos > openPos.sql
python3 ./_scripts/csv2psql.py ./_data_csv/pastCourses.csv pastCourses > pastCourses.sql
python3 ./_scripts/csv2psql.py ./_data_csv/phdAlumni.csv phdAlumni > phdAlumni.sql
python3 ./_scripts/csv2psql.py ./_data_csv/placement.csv placement > placement.sql
python3 ./_scripts/csv2psql.py ./_data_csv/postdoc.csv postdoc > postdoc.sql
python3 ./_scripts/csv2psql.py ./_data_csv/projects.csv projects > projects.sql
python3 ./_scripts/csv2psql.py ./_data_csv/scholars.csv scholars > scholars.sql
python3 ./_scripts/csv2psql.py ./_data_csv/seminars.csv seminars > seminars.sql
python3 ./_scripts/csv2psql.py ./_data_csv/staff.csv staff > staff.sql
python3 ./_scripts/csv2psql.py ./_data_csv/stats.csv stats > stats.sql
python3 ./_scripts/csv2psql.py ./_data_csv/talks.csv talks > talks.sql
python3 ./_scripts/csv2psql.py ./_data_csv/talkseries.csv talkseries > talkseries.sql
python3 ./_scripts/csv2psql.py ./_data_csv/workshops.csv workshops > workshops.sql
