Insert into "placement"("registered", "year", "prog", "range", "count") values ('27', '2020', 'UG', '6 LPA - 10 LPA', '8');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('27', '2020', 'UG', '10 LPA - 20 LPA', '7');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('27', '2020', 'UG', '20 LPA - 30 LPA', '11');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('27', '2020', 'UG', '30 LPA and above', '1');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('42', '2021', 'UG', '6 LPA - 10 LPA', '7');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('42', '2021', 'UG', '10 LPA - 20 LPA', '23');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('42', '2021', 'UG', '20 LPA - 30 LPA', '8');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('42', '2021', 'UG', '30 LPA and above', '4');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('50', '2022', 'UG', '6 LPA - 10 LPA', '6');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('50', '2022', 'UG', '10 LPA - 20 LPA', '19');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('50', '2022', 'UG', '20 LPA - 30 LPA', '12');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('50', '2022', 'UG', '30 LPA and above', '13');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('7', '2022', 'MCaM', '7.5 LPA - 10 LPA', '3');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('7', '2022', 'MCaM', '10 LPA - 20 LPA', '4');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('7', '2022', 'MCaM', '20 LPA - 30 LPA', '0');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('7', '2022', 'MCaM', '30 LPA and above', '0');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('5', '2021', 'MCaM', '7.5 LPA - 10 LPA', '3');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('5', '2021', 'MCaM', '10 LPA - 20 LPA', '2');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('5', '2021', 'MCaM', '20 LPA - 30 LPA', '0');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('5', '2021', 'MCaM', '30 LPA and above', '0');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('13', '2021', 'MSoCD', '6 LPA - 10 LPA', '2');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('13', '2021', 'MSoCD', '10 LPA - 20 LPA', '2');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('13', '2021', 'MSoCD', '20 LPA - 30 LPA', '7');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('13', '2021', 'MSoCD', '30 LPA and above', '0');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('8', '2022', 'MSoCD', '7.5 LPA - 10 LPA', '1');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('8', '2022', 'MSoCD', '10 LPA - 20 LPA', '3');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('8', '2022', 'MSoCD', '20 LPA - 30 LPA', '2');
Insert into "placement"("registered", "year", "prog", "range", "count") values ('8', '2022', 'MSoCD', '30 LPA and above', '1');
